name: CI

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2

    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -Dwarnings
    - run: cargo build
    - run: cargo test --no-fail-fast
    - run: cargo doc --no-deps

    - run: cp -r utils/github-pages/* target/doc
    - run: |
        chmod -c -R +rX "target/doc/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
    - uses: actions/upload-pages-artifact@v2
      with:
        path: target/doc

  deploy:
    if: github.ref_name == 'master'
    name: Deploy
    needs: ci
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
